name: Feature Request
description: Request a feature that you think should be added.

title: "[FEATURE] Title"
labels: feature

body:
- type: checkboxes
  id: existing-issue
  attributes:
    label: Is there an existing request for this feature?
    description: Search for an existing request to avoid duplicate requests.
    options:
    - label: I have searched for an [existing request](https://github.com/EasyScriptJS/EasyScript/issues).
      required: true
- type: input
  id: what
  attributes:
    label: What?
    description: What feature do you want to be added?
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description
    description: Provide a description of the feature you want added.
  validations:
    required: true
- type: textarea
  id: why
  attributes:
    label: Why?
    description: Why should this feature be added?
  validations:
    required: false
